### PR TITLE
Ensure exception thrown when error installing or uninstalling service - Fixes #7

### LINKED ISSUE #7: Convert xADCSWebEnrollment to use IsSingleInstance resource design pattern
The xADCSWebEnrollment resource currently requires a Name key field that gives the impression that more than one instance could be installed.

I think it should be updated to use the IsSingleInstance design pattern as defined in [this post](
http://blogs.msdn.com/b/powershell/archive/2015/06/23/want-to-write-a-dsc-resource-where-only-a-single-instance-can-be-configured.aspx).

### LINKED ISSUE #29: Update to use Shared AppVeyor module

### LINKED ISSUE #32: Migrate Pester Test Syntax from v3 -> v4
**Details of the scenario you tried and the problem that is occurring:**
As of Pester v4 the syntax of the `Should` cmdlet has changed from `Should Be` to `Should -Be`.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

### LINKED ISSUE #33: Update to meet HQRM guidelines
This module does not currently meet HQRM guidelines. It needs to be updated.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR primarily fixes an issue where an exception is not thrown by the resource when a domain credential is wrong which results in down stream issues.

But as part of this I migrated the resource module to meet HQRM as I assumed this would get pulled up in the code review anyway.

**This Pull Request (PR) fixes the following issues:**
- Fixes #7 
- Fixes #32 
- Fixes #29 
- Fixes #33

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@Johlju - hopefully this is the last of the large HQRM changes I'll be doing! If you get a moment or lots (there is definitely no rush at all) would you mind? We really need some other reviewers around here so that I don't have to call on you every single time! :grin:

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xadcsdeployment/34)

### CODE REVIEW

**Comment by johlju** [comment]
I don't mind being tagged on PR needing review. I'm happy to do them as soon as I can. :smile: 

Just a few minor comments.


Btw. how come you get "Impacted files" on your code coverage reports in the PR's. :thinking:  I don't get those in xSQLServer. :smile: 

---

Reviewed 20 of 26 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[README.md, line 4 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyejRT_ycN6Z3tEskV2:-KyejRT_ycN6Z3tEskV3:b-txpbx5) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L4)):*
> Windows Server 2012 R2

Maybe just 'Windows Server'? Or does this module only work with 2012 R2? Not 2016 and above?

---

*[README.md, line 53 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyek-bgL2NHbbcJWYbE:-Kyek-bgL2NHbbcJWYbF:b-h2112r) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L53)):*
> ```Markdown
> - **xAdcsWebEnrollment**: This resource can be used to install the ADCS Web
>   Enrollment service after the feature has been installed on the server.
> - **xAdcsOnlineResponder**: This resource can be used to install an ADCS Online
> ```

Maybe move these in alphabetical order?

---

*[README.md, line 66 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyekfTeNQSXpDIxj8dC:-KyekfTeNQSXpDIxj8dD:b25na7f) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L66)):*
> ```Markdown
>   install. { EnterpriseRootCA | EnterpriseSubordinateCA | StandaloneRootCA |
>   StandaloneSubordinateCA }
> - **`[System.Management.Automation.PSCredential]` Credential** (_Required_): To
> ```

Maybe we just use 'PSCredential' here since the others aren't using the full namespace?

---

*[README.md, line 82 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyelP80L2PkH6X5BU9G:-KyelP80L2PkH6X5BU9H:b-cxfbnl) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L82)):*
> ```Markdown
> - **`[String]` CertFile** (_Write_): Specifies the file name of certification
>   authority PKCS 12 formatted certificate file.
> - **`[System.Management.Automation.PSCredential]` CertFilePassword** (_Write_):
> ```

Same as previous comment.

---

*[README.md, line 137 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyelm_yVcT2I4O-3em6:-Kyelm_yVcT2I4O-3em7:bo9fsdb) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L137)):*
> ```Markdown
> - **`[String]` CAConfig** (_Write_): CAConfig parameter string. Do not specify
>   this if there is a local CA installed.
> - **`[System.Management.Automation.PSCredential]` Credential** (_Required_): If
> ```

same as previous comment.

---

*[README.md, line 161 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyem61kd2u4g6CT_Dcp:-Kyem61kd2u4g6CT_Dcq:b-cxfbnl) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L161)):*
> ```Markdown
> - **`[String]` CAConfig** (_Write_): CAConfig parameter string. Do not specify
>   this if there is a local CA installed.
> - **`[System.Management.Automation.PSCredential]` Credential** (_Required_): If
> ```

Same as previous comment.

---

*[DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1, line 98 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyeqHwp1gaV4BUrxX4S:-KyeqHwp1gaV4BUrxX4T:b-v640ut) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1#L98)):*
> ```PowerShell
> Function Get-TargetResource
> {
>     [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSShouldProcess', '')]
> ```

We should remove this since ShouldProcess is not supported by LCM. Throughout the resources.

---

*[DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyemz_mWZZb6EywzZLX:-Kyemz_mWZZb6EywzZLY:bnyvtk8) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1#L99)):*
> ```PowerShell
> {
>     [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSShouldProcess', '')]
>     [CmdletBinding(SupportsShouldProcess = $true)]
> ```

We should remove 'SupportsShouldProcess' since that is not supported of LCM. Throughout the resources.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-:-KyetiqW60OJrnm2AXmK:bkg7is3)*

**Comment by johlju** [comment]
We probably get a different codecov layout here because the CodeCov yaml file hasn't been merged, so it is using [the default yaml file](https://docs.codecov.io/docs/codecov-yaml#section-default-yaml). Once merged, it will look the same.

**Comment by PlagueHO** [comment]
@Johlju - I do really appreciate how much time you put into all of these reviews though! :grin:

As for the "Impacted files" - I'm not sure - that doesn't normally show up for me either. Perhaps a new feature from codecov? Or perhaps only happens with repos that have never had code coverage before?

---

Review status: 21 of 25 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 4 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyejRT_ycN6Z3tEskV2:-KyggNiu_qp7KCHHWXyj:beervgw) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Windows Server 2012 R2

Maybe just 'Windows Server'? Or does this module only work with 2012 R2? Not 2016 and above?
</blockquote></details>

Good call. This does also work on Windows Server 2016 - so have corrected it.

---

*[README.md, line 53 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyek-bgL2NHbbcJWYbE:-Kygg_AV3-DCQaX31bdc:bo3n7jv) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L53)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe move these in alphabetical order?
</blockquote></details>

Another good call. Done.

---

*[README.md, line 66 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyekfTeNQSXpDIxj8dC:-Kyggh-yz9u8XStxLnvb:b-896fix) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L66)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we just use 'PSCredential' here since the others aren't using the full namespace?
</blockquote></details>

Done.

---

*[README.md, line 82 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyelP80L2PkH6X5BU9G:-KygghVDBfSZyfG_F5NG:b-896fix) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L82)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

Done.

---

*[README.md, line 137 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyelm_yVcT2I4O-3em6:-Kygghr6gowj6IlBYzcb:b-896fix) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L137)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

same as previous comment.
</blockquote></details>

Done.

---

*[README.md, line 161 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyem61kd2u4g6CT_Dcp:-KyggieoUeK_gLkvYN8b:b-896fix) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/README.md#L161)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1, line 98 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-KyeqHwp1gaV4BUrxX4S:-KyghDQjkPcndpsPnbjo:bqenai2) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1#L98)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should remove this since ShouldProcess is not supported by LCM. Throughout the resources.
</blockquote></details>

Good call. Have removed all instances (and from other resources).

---

*[DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-Kyemz_mWZZb6EywzZLX:-KyghHGtL-NB8kbnjEXq:bqenai2) ([raw file](https://github.com/powershell/xadcsdeployment/blob/88a1dc55bde89b4e84e0e48fb605ae8358e18ae6/DSCResources/MSFT_xAdcsCertificationAuthority/MSFT_xAdcsCertificationAuthority.psm1#L99)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should remove 'SupportsShouldProcess' since that is not supported of LCM. Throughout the resources.
</blockquote></details>

Good call. Have removed all instances (and from other resources).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-:-KygfBcntBnMqdPO7em-:b6sn6rm)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/34#-:-Kyjmqkgj1noQHGnZvAs:bnfp4nl)*

**Pull request merged**
